### ISSUE TITLE
Change reference to SolaceLabs?

### ISSUE THREAD

**Issue by ShawnMcAllister** [dickeyf/openshift-aws-install#1]
Now that the base project is in SolaceLabs, should we change this for non-Solace users?

git clone https://github.com/SolaceDev/openshift-VMR-howto.git

**Comment by dickeyf** [comment]
I will change it to : git clone https://github.com/dickeyf/openshift-aws-install.git

I will also add a reference to "https://github.com/SolaceDev/openshift-VMR-howto.git" to point people to a demo which they can load to try the newly created Openshift environment.

**Comment by dickeyf** [comment]
Addressed this issue in : https://github.com/dickeyf/openshift-aws-install/commit/cfe72a9142d8a6ce8d6e53a91d5243a9e24db924
